---
galaxy_info:
  author: Vishal Shah
  description: Setup bash_profile
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - bash_profile

dependencies: []
