---
- hosts: great_server
  roles:
    - consul1
    - nginx
    - pip
    - elasticsearch
    - rabbitmq
    - rabbitmq_exchange
    - messaging
    - kibana-4
    - elk
    - jenkins2
    - activemq
    - ssh_keys_db
    - barman
    - postgresql
    - redis
    - uchiwa
    #- sensu
    #- sensu_plugins
