#general servers ip
filebeat_logstash_host: 192.168.100.102
#consul_server: 192.168.100.104
#barman_server: 192.168.100.109
#dns_server: 10.10.10.11
#sensu::server::ip: 192.168.100.106

consul_server: 192.168.100.120
barman_server: 192.168.100.120
dns_server: 10.10.10.11
sensu::server::ip: 192.168.100.120


consul_master: "{{ consul_server }}"

resolv_conf_nameservers:
      - 127.0.0.1
      - "{{ dns_server }}"
      - 8.8.8.8
resolv_conf_search_domains:
      - paosin.local
      - node.consul

java_packages:
  - "java-1.8.0-openjdk"
  - "java-1.7.0-openjdk"


        
#consul
consul_clients_group: all
consul_bind_interface: eth1
consul_enable_dnsmasq: false

consul_servers_group: "consul_servers"
consul_version: 0.7.2

consul_datacenter: "paosin-ansible"


consul_is_server: false
consul_bootstrap: false
consul_bind_address: "{{ ansible_eth1.ipv4.address  }}"
consul_node_name: "{{ ansible_fqdn }}"
consul_use_systemd: true
consul_advertise_address: "{{ ansible_eth1.ipv4.address  }}"
consul_servers: ["{{consul_server}}"]
consul_join_at_start: true
consul_log_level: "DEBUG"
consul_dns_config: false
consul_recursors: 
 - "{{ dns_server }}"

consul_group_name: sensu_servers
consul_node_role: client

influxdb_server: "influxdb.service.{{consul_datacenter}}.consul"

sensu::server: "sensu.service.{{consul_datacenter}}.consul"
rabbitmq::host: "rabbitmq.service.{{consul_datacenter}}.consul"

postgresql_server1: "postgresql.service.{{consul_datacenter}}.consul"
#sensu_ssl_gen_certs: true
#sensu_deploy_rabbitmq: false

#sensu_deploy_redis: false
#
#rabbitmq_port: 5672

#sensu_api_host:  "sensu.service.{{consul_datacenter}}.consul"

rabbitmq_host: "rabbitmq.service.{{consul_datacenter}}.consul"
elasticsearch_host: "elasticsearch.service.{{consul_datacenter}}.consul"
server__sensu: "sensu.service.{{consul_datacenter}}.consul"

sensu_plugins_directory: "/opt/sensu/embedded/bin" #"/etc/sensu/plugins" #"/opt/sensu/embedded/bin" # 
sensu_ruby_path: "/opt/sensu/embedded/bin/ruby"

sensu_rabbitmq_host: "{{ rabbitmq_host }}"
sensu_rabbitmq_port: 5672
sensu_rabbitmq_user: sensu
sensu_rabbitmq_password: sensu
sensu_rabbitmq_vhost: /sensu
sensu_install_server: false
sensu_install_api: false
sensu_install_client: true

sensu_redis_host: "redis.service.{{consul_datacenter}}.consul"
sensu_api_host: "sensu.service.{{consul_datacenter}}.consul"

# Default sensu-client config variables
sensu_client_name: "{{ ansible_hostname }}"
sensu_client_address: "{{ ansible_eth1.ipv4.address }}"
sensu_client_subscriptions:
  - ALL



firewalld_allow_services:
  - { service: "ssh" ,  zone: public ,  permanent: True  ,  state: enabled  }
  
firewalld_allow_ports:
  - { port: 8301/tcp , zone: public , state: enabled } 
  #- { port: 8300/tcp , zone: public , state: enabled } 
  #- { port: 8302/tcp , zone: public , state: enabled }
  #- { port: 8500/tcp , zone: public , state: enabled }
  #- { port: 8600/udp , zone: public , state: enabled }
  #- { port: 8543/tcp , zone: public , state: enabled }
  
#beats
beat_name: filebeat
beat_config:
  filebeat:
    prospectors:
      - paths:
          - "/var/log/de/*.log"
        document_type: "de-log"
    output:
      logstash:
        hosts:
          - "{{filebeat_logstash_host}}"
        index: "{{filebeat_index_pattern}}"
    shipper:
      name: "{{ansible_hostname}}"
      tags: 
        - "{{ inventory_file.split('/')[-1].split('.')[0] }}"
    logging:
     to_files: true
     level: info
     files:
       path: /var/log/filebeat
       name: filebeat
       rotateeverybytes: 10485760
       
       
dynamic_data_store: /etc/dynamic

#logstash
logstash_configs:
  - 01-agent-input.conf
  - 02-agent-output.conf
  - 03-agent-filter.conf
  
#metric



telegraf_plugins:
  - name: mem
  - name: statsd
  - name: nginx
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      fielddrop:
        - "time_*"
  - name: disk
    options:
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: procstat
    options:
      exe: "influxd"
      prefix: "influxdb"
      
      
# Syslog plugin
collectd_plugins_syslog_loglevel: info

collectd_plugins_syslog:
  - options:
    - LoadPlugin: syslog
  - sections:
    - name: Plugin
      param: syslog
      content:
        - options:
          - LogLevel: "{{ collectd_plugins_syslog_loglevel }}"


collectd_plugins_network:
  - options:
    - LoadPlugin: network
  - sections:
    - name: Plugin
      param: network
      content:
        - options:
          - Server: "{{ influxdb_server }}:25826"
          
#Server "192.168.0.42" "25827"
# CPU plugin
collectd_plugins_cpu:
  - options:
    - LoadPlugin: cpu

#DISK
collectd_plugins_disk:
  - options:
    - LoadPlugin: disk
  - sections:
    - name: Plugin
      param: disk
      content:
        - options:
          - Disk: "sda"
          - Disk: "/^hd/"
          - IgnoreSelected: "false"
    
# Interface plugin
collectd_plugins_interface:
  - options:
    - LoadPlugin: interface

 
# Load plugin
collectd_plugins_load:
  - options:
    - LoadPlugin: load

# df plugin
collectd_plugins_df:
  - options:
    - LoadPlugin: df

collectd_plugins_fhcount:
  - options:
    - LoadPlugin: fhcount
    
# Memory plugin
collectd_plugins_memory:
  - options:
    - LoadPlugin: memory


# Plugins definitions
collectd_plugins_default: "{{
  collectd_plugins_syslog +
  collectd_plugins_cpu +
  collectd_plugins_interface +
  collectd_plugins_load +
  collectd_plugins_memory + 
  collectd_plugins_network + 
  collectd_plugins_disk +
  collectd_plugins_df + 
  collectd_plugins_fhcount
}}"