#general servers ip
filebeat_logstash_host: 192.168.100.102
consul_server: 192.168.100.105



dns_server: 10.10.10.11

resolv_conf_nameservers:
      - 127.0.0.1
      - 10.10.10.11
      - 8.8.8.8
resolv_conf_search_domains:
      - paosin.local
      - node.consul

java_packages:
  - java-1.8.0-openjdk

#consul
consul_version: 0.7.0
consul_datacenter: "paosin-ansible"
consul_is_server: false
consul_bootstrap: false
consul_bind_address: "{{ ansible_eth1.ipv4.address  }}"
consul_node_name: "{{ ansible_fqdn }}"
consul_use_systemd: true
consul_advertise_address: "{{ ansible_eth1.ipv4.address  }}"
consul_servers: ["{{consul_server}}"]
consul_join_at_start: true
consul_log_level: "DEBUG"
consul_dns_config: false
consul_recursors: 
 - 10.10.10.11


sensu::server::ip: 192.168.100.106
sensu::server: "sensu.service.{{consul_datacenter}}.consul"
rabbitmq::host: "rabbitmq.service.{{consul_datacenter}}.consul"

#sensu_ssl_gen_certs: true
#sensu_deploy_rabbitmq: false

#sensu_deploy_redis: false
#
#rabbitmq_port: 5672

#sensu_api_host:  "sensu.service.{{consul_datacenter}}.consul"

rabbitmq_host: "rabbitmq.service.{{consul_datacenter}}.consul"

server__sensu: "sensu.service.{{consul_datacenter}}.consul"

sensu_plugins_directory: /opt/sensu/embedded/bin/ruby


sensu_install_server: false
sensu_install_api: false
sensu_install_client: true

sensu_checks:
  - name: check_cron
    command: "{{ sensu_plugins_directory }}/check-procs.rb -d cron -C 1"
  - name: check_cron
    command: "{{ sensu_plugins_directory }}/check-disk-usage.rb -w 80 -c 90"  




#beats
beat_name: filebeat
beat_config:
  filebeat:
    prospectors:
      - paths:
          - "/var/log/de/*.log"
        document_type: "de-log"
    output:
      logstash:
        hosts:
          - "{{filebeat_logstash_host}}"
        index: "{{filebeat_index_pattern}}"
    shipper:
      name: "{{ansible_hostname}}"
      tags: 
        - "{{ inventory_file.split('/')[-1].split('.')[0] }}"
    logging:
     to_files: true
     level: info
     files:
       path: /var/log/filebeat
       name: filebeat
       rotateeverybytes: 10485760
       
       
dynamic_data_store: /etc/dynamic