barman_upstreams:
  - name: "db1"
    hostname: "{{ postgresql_server1 }}"

firewalld_allow_ports:
  - { port: 5432/tcp , zone: public , state: enabled }
  - { port: 8301/tcp , zone: public , state: enabled }
        
consul_services:
  - service:
      name: "barman"
      tags:
        - "barman"
      port: 5432
      checks:
        - name: "Barman health check"
          tcp: "localhost:5432"
          interval: "10s"
          timeout: "1s"