consul_is_server: "true"
consul_bootstrap: "true"
consul_is_ui: true

consul_ui_server_port: 85
consul_install_nginx: true


consul_node_role: bootstrap
consul_group_name: consul_servers

firewalld_allow_ports:
  - { port: 8500 , zone: public , state: enabled } 

consul_services:
  - service:
      name: "consul_server"
      tags:
        - "consul_server"
      port: 8500
      checks:
        - name: "RabbitMQ health check"
          tcp: "localhost:8500"
          interval: "10s"
          timeout: "1s"

              
#"{{ ansible_fqdn }}"
#"{{ inventory_hostname }}"