consul_is_server: "true"
consul_bootstrap: "true"
consul_is_ui: true

consul_ui_server_port: 85
consul_install_nginx: true



consul_services:
  - service:
      name: "consul_server"
      tags:
        - "consul_server"
      address: "localhost"
      port: 8500
      checks:
        - name: "Consul health check"
          http: "http://localhost"
          interval: "10s"
          timeout: "1s"
          
#"{{ ansible_fqdn }}"
#"{{ inventory_hostname }}"