consul_is_server: "true"
consul_bootstrap: "true"
consul_bind_address: "{{ ansible_eth1.ipv4.address }}"
consul_use_systemd: true
consul_is_ui: true
consul_node_name: "{{ ansible_fqdn }}"
consul_log_level: "DEBUG"
consul_use_initd: true

consul_services:
  - service:
      name: "localhost"
      tags:
        - "httpd"
      address: "localhost"
      port: 80
      checks:
        - name: "Consul health check"
          http: "http://localhost"
          interval: "10s"
          timeout: "1s"
          
#"{{ ansible_fqdn }}"
#"{{ inventory_hostname }}"