sensu_install_server: true
sensu_install_api: true

redis_bind_interface: 0.0.0.0


sensu_client_subscriptions:
  - ALL
  - REDIS
  - SENSU

uchiwa_sensu_site: "{{consul_datacenter}}"
uchiwa_user: admin
uchiwa_pass: admin

sensu_redis_host: localhost
sensu_redis_port: 6379

firewalld_allow_ports:
  - { port: "{{ sensu_redis_port }}" , zone: public , state: enabled }
  - { port: 3000 , zone: public , state: enabled }
  - { port: 4567 , zone: public , state: enabled }
  
consul_services:
  - service:
      name: "redis"
      tags:
        - "redis"
      port: "{{ sensu_redis_port }}"
      checks:
        - name: "redis health check"
          tcp: "localhost:{{ sensu_redis_port }}"
          interval: "10s"
          timeout: "1s"
  - service:
      name: "uchiwa"
      tags:
        - "uchiwa"
      port: 3000
      checks:
        - name: "Uchiwa health check"
          tcp: "localhost:3000"
          interval: "10s"
          timeout: "1s"
  - service:
      name: "sensu"
      tags:
        - "sensu"
      port: 4567
      checks:
        - name: "Sensu Stomp health check"
          tcp: "localhost:4567"
          interval: "10s"
          timeout: "1s"