---
- include: server_roles/all_servers.yml
- include: server_roles/web_servers.yml
- include: server_roles/consul_servers.yml
- include: server_roles/elk_servers.yml
- include: server_roles/sensu_servers.yml
- include: server_roles/messaging_servers.yml
- include: server_roles/barman_servers.yml
- include: server_roles/postgres_servers.yml
- include: server_roles/jenkins_servers.yml
- include: server_roles/great_server.yml
- include: server_roles/ha_servers.yml
#- include: server_roles/db_servers.yml