# Fetch metrics about the CPU load every 60 seconds,
# the sensu server has a handler called 'relay' which forwards stats to graphite
- name: get cpu metrics
  sensu_check:
    name: cpu_load
    command: "{{ sensu_ruby_path }} {{ sensu_plugins_directory }}/cpu-mpstat-metrics.rb"
    metric: yes
    handlers: relay
    subscribers: ALL
    interval: 60

- name: get hdd metrics
  sensu_check:
    name: check-disk-usage
    command: "{{ sensu_ruby_path }} {{ sensu_plugins_directory }}/check-disk-usage.rb -w 80 -c 90"
    metric: yes
    handlers: default
    subscribers: ALL
    interval: 60
- name: get selinx metrics
  sensu_check:
    name: check-selinux
    command: "{{ sensu_ruby_path }} {{ sensu_plugins_directory }}/check-selinux.rb"
    metric: yes
    handlers: default
    subscribers: ALL
    interval: 60    
# Check whether nginx is running
- name: check nginx process
  sensu_check:
    name: nginx_running
    command: "{{ sensu_ruby_path }} {{ sensu_plugins_directory }}/check-procs.rb -f /var/run/nginx.pid"
    handlers: default
    subscribers: nginx
    interval: 60
