---
# included file

- name: Jenkins RPM Key
  environment:
    http_proxy: "{{ jenkins2_rpm_key_proxy_url }}"
    HTTP_PROXY: "{{ jenkins2_rpm_key_proxy_url }}"
    https_proxy: "{{ jenkins2_rpm_key_proxy_url }}"
    HTTPS_PROXY: "{{ jenkins2_rpm_key_proxy_url }}"
  rpm_key:
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    validate_certs: "{{ jenkins2_rpm_key_validate_certs }}"
    state: present
  become: yes

- name: GoogleChrome YUM Repository
  yum_repository:
    name: google-chrome
    description: GoogleChrome YUM Repository
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgcheck: yes
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes
  
- name: Jenkins YUM Repository
  yum_repository:
    name: jenkinsrepo
    description: Jenkins YUM Repository
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: yes
    state: present
  become: yes

- name: Jenkins Installation
  yum:
    name: "{{ jenkins2_version }}"
    disable_gpg_check: "{{ jenkins2_disable_gpg_check }}"
    state: present
  become: yes

- name: google-chrome-stable Installation
  yum:
    name: "google-chrome-stable"
    state: present
  become: yes
  with_items:
    - google-chrome-stable
    - GConf2
  
- name: Create Logstash filters.
  copy:
    src: "chromedriver"
    dest: "/var/lib/jenkins"
    owner: jenkins
    group: jenkins
    mode: 0644
