- easy_install:
    name: requests
    state: latest

- name: selinux port open 15672
  shell: setsebool -P nis_enabled 1
  args:
   executable: /bin/bash

- name:  restart rabbitmq-server
  shell: systemctl restart rabbitmq-server
  args:
   executable: /bin/bash
   

  
  
#4369 5672, 5671 25672 15672 61613, 61614 1883, 8883
  
  
# Create topic exchange on vhost
- rabbitmq_exchange: name=exchangelogstash type=topic vhost=/logstash  login_user=logstash login_password=logstash

# Create a queue on remote host
- rabbitmq_queue: name=queuelogstash vhost=/logstash login_user=logstash login_password=logstash

# Bind myQueue to directExchange with routing key info
- rabbitmq_binding: name=exchangelogstash destination=queuelogstash vhost=/logstash type=queue login_user=logstash login_password=logstash

# Bind directExchange to topicExchange with routing key *.info
#- rabbitmq_binding: name=topicExchange destination=topicExchange type=exchange routingKey="logs.%{host}"